config/routes.rb
Rails.application.routes.draw do
  
  #Cadastro de usuários
  # - Atenção : 'resouces' com 's' possui rota automática para index! No singular, não (vai para show)
  resources :cadastros

  devise_for :users ,
             controllers: {registrations: 'users/registrations'}  #redireciona para controle customizado
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Redireciona para o login sempre que for para a página inicial
  # https://stackoverflow.com/questions/4954876/setting-devise-login-to-be-root-page
  devise_scope :user do
    authenticated :user do
      root 'home#index' , as: :authenticated_root
    end

    unauthenticated  do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  root 'home#index'
end

app/models/cadastro.rb
class Cadastro < ApplicationRecord
    validates  :matricula , :email,  :nome, :tipo ,:password, presence : true
end

app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
    
    helper CadastroHelper  

    def index
      @cadastros = User.all
    end
    def show
      @cadastro = User.find(params[:id])
    end

    def new
      @cadastro = User.new
    end

    def edit
      @cadastro = User.find(params[:id])
    end

    def create
        @cadastro = User.new(cadastro_params)
        
        puts "----- entra cadastro.save #{@cadastro}"
        @cadastro.save
        if @cadastro.save
            redirect_to cadastros_path
            puts "-----cadastro.save"
          else
            puts "-----nao salvou"
            render :new
        end
    end

    def update
      puts "----- entra update.save #{@cadastro}"
      @cadastro = User.find(params[:id]) 
       puts "-------update  #{@cadastro}"
      if @cadastro.update(cadastro_params)
        redirect_to cadastros_path
        puts "--------cadastro.update"
      else
        puts "--------cdastro nao editou!"
        render :edit
      end 

    end

    def destroy
        @cadastro = User.find(params[:id])
        puts "---destroy id #{@cadastro.id}"
        @cadastro.destroy

        redirect_to cadastros_path
    end
  

    private

    #Usuários administradores realizam cadastro
    def cadastro_params
      params.require(:user).permit(:email, :matricula, :nome , :password , :tipo)
    end
    
end

app/helpers/cadastro_helper.rb
module CadastroHelper
    #Métodos para fazer visível a variável resource_name do Devise no módulo de Cadastro
    def resource_name
        :user
    end

    def resource
        @resource ||= User.new
    end

    def devise_mapping
        @devise_mapping ||=Devise.mappings[:user]
    end
end

app/views/cadastros/_form.html.erb
<%= form_with model: @cadastro, url: url , method: method  do |form|  %>     
    <% if @cadastro.errors.any? %>
        <div id="error">
            <h4>
                <%= pluralize(@cadastro.errors.count, "Erro :", plural: "Erros :")%>
            </h4>
            <ul>
                <% @cadastro.errors.full_messages.each do |error|%>
                    <li>
                        <%= error %>
                    </li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="div_table">
        <div class="div_tr">
            <div class="div_td_right"> <%= form.label t('login') %> </div>
            <div class="div_td_left"> <%= form.text_field :matricula ,autofocus: true , disabled: is_disabled %> </div>
        </div>
        <div class="div_tr">
            <div class="div_td_right"> <%= form.label t('nome')%> </div>
            <div class="div_td_left"> <%= form.text_field :nome , disabled: is_disabled%> </div>
        </div>
        <div class="div_tr">
            <div class="div_td_right"> <%= form.label t('email')%> </div>
            <div class="div_td_left"> <%= form.text_field :email ,  autocomplete: "email" , disabled: is_disabled%> </div>
        </div>
        <% if @cadastro.new_record? %>
            <div class="div_tr">
                <div class="div_td_right"> <%= form.label t('password') %> </div>
                <% if @minimum_password_length %>
                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                <% end %>
                <div class="div_td_left"> <%= form.password_field :password, autocomplete: "new-password" %> </div>
            </div>

            <div class="div_tr">
                <div class="div_td_right"> <%= form.label t('password_confirmation') %> </div>
                <div class="div_td_left"> <%= form.password_field :password_confirmation, autocomplete: "new-password" %> </div>
            </div>
        <% end %>
        <div class="div_tr">
            <div class="div_td_right"> <%= form.label t('tipo')%> </div>
            <!--TODO: dropdownlist vai aqui!-->
        </div>
    </div>

        <br/>
    <% unless is_disabled %>
    <div class="div_table">
        <div class="div_tr">
            <%= form.submit t('enviar'), class: "submit"%>
        </div>
    </div>
    <% end %>
<% end %>
<br/>
<div class="div_table">
    <%= link_to "Início", root_path %>
</div>

app/views/cadastros/edit.html.erb
<h2>Editar informações do usuário</h2>

<%= render partial: 'form' , locals: {url: cadastro_path, method: :put, is_disabled: false}%>

app/views/cadastros/index.html.erb
<h2> Usuários cadastrados </h2>

<div >
<table>
    <tr>
        <th class="matricula">Matrícula</th>
        <th class="nome">Nome</th>
        <th class="email">Email</th>
        <th class="tipo">Tipo</th>
        <th class="action"></th>
        <th class="action"></th>
        <!--
        <th class="action"></th>
        -->
    </tr>

    <% @cadastros.each do |cadastro| %>
    <tr>
        <td>
            <%= cadastro.matricula%>
        </td>
        <td>
            <%= cadastro.nome%>
        </td>
        <td>
            <%= cadastro.email%>
        </td>
        <td>
            <%= cadastro.tipo%>
        </td>
        <td class="center">
            <%= link_to "Visualizar", cadastro_path(cadastro) %>
        </td>
        <td class="center">
            <%= link_to "Editar", edit_cadastro_path(cadastro)%>
        </td>
        <!--TODO: validar se é usuário corrente
        <td class="center">
            <%= link_to "Excluir", cadastro_path(cadastro),
                                    method: :delete,
                                    data: {confirm: "Tem certeza que deseja excluir o usuário?"}%>
        </td>
        -->
    </tr>
    <% end %>
</table>
<div>
<br/>
<div class="div_table">
    <%= link_to "Início", root_path %>
</div>    

app/views/cadastros/new.html.erb
<h2>Criar novo usuário</h2>

<%= render partial: 'form' , locals: {url: cadastros_path , method: :post, is_disabled: false}%>

app/views/cadastros/show.html.erb
<h2> Dados do Usuário </h2>

<%= render partial: 'form' , locals: {url: cadastro_path, method: :get, is_disabled: true}%>